name: Create dynamic env 

on: 
  create:
  push:
    branches-ignore:
      - 'develop'

  delete:
    branches:
      - '*'
      - '!main'
      - '!develop'
      - '!uat'
permissions:
  contents: write
env: 
  AWS_REGION: eu-central-1
  REPOSITORY_NAME: "hello"
  AWS_ECR: "211125572880.dkr.ecr.eu-central-1.amazonaws.com"
  IMAGE_TAG: ${{ github.ref_name }}
  DOCKERFILE: ./app/Dockerfile
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
jobs:  
  build-push-img:
    if: |
      github.event_name == 'create' ||
      (github.event_name == 'push' && startsWith(github.event.head_commit.message, 'push'))
    runs-on: ubuntu-latest
    steps:
      - name: Get branchy name
        run: |
          echo ${{ github.ref_name }}

      - name: Checkout codebase
        uses: actions/checkout@v4
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          docker build -t $AWS_ECR/$REPOSITORY_NAME:$IMAGE_TAG -f $DOCKERFILE ./app 
          docker push $AWS_ECR/$REPOSITORY_NAME:$IMAGE_TAG

  create-new-fargate:
    if: ${{ github.event_name == 'create' && github.event.ref_type == 'branch' }} || ${{github.event_name == 'delete' }}
    runs-on: ubuntu-latest
    needs: ${{ github.event_name == 'create' && github.event.ref_type == 'branch' && 'build-push-img' || github.event_name == 'delete' && '[]' }}
    steps:
      - name: Checkout infra-branch-env
        uses: actions/checkout@v4
        with:
          ref: env-infra
      

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Set up git remote URL
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

     
      - name: Add  ${{ github.ref_name }} to list preview 
        if: ${{ github.event_name == 'create' && github.event.ref_type == 'branch' }}
        run: |
          cd ./.infrastructure/fargate
          sh ../../.github/scripts/edit_pr_list.sh add ${{ github.ref_name }}
          git add variable.tf
          git commit -m '${{ github.ref_name }}' || echo "nothing to commit"
          git push || echo "nothing to push"
        env:
          GITHUB_TOKEN: $GITHUB_TOKEN

      - name: Rm  ${{ github.ref_name }} to list preview 
        if: ${{ github.event_name == 'delete'}}
        run: |
          cd ./.infrastructure/fargate
          sh ../../.github/scripts/edit_pr_list.sh rm ${{ github.ref_name }}
          git add variable.tf
          git commit -m '${{ github.ref_name }}' || echo "nothing to commit"
          git push || echo "nothing to push"
        env:
          GITHUB_TOKEN: $GITHUB_TOKEN

          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform congigure
        run: |
          pwd 
          ls -l
          cd ./.infrastructure/fargate
          pwd 
          ls -l
          terraform init -backend-config=backend.tfvars
          terraform plan
          terraform apply -auto-approve
          




